using BookTour.Dto.Common;
using BookTour.Dto.Request;
using BookTour.Dto.Response;
using BookTour.Models;
using BookTour.Repository;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookTour.Service.Impl
{
    public class TourismCompanyService : ITourismCompanyService
    {
        private readonly ITourismCompanyRepository _companyRepository;
        private readonly BookTourContext _context;

        public TourismCompanyService(ITourismCompanyRepository companyRepository, BookTourContext context)
        {
            _companyRepository = companyRepository;
            _context = context;
        }

        public async Task<ApiResponse<List<TourismCompanyResponse>>> GetAllCompaniesAsync()
        {
            try
            {
                var companies = await _companyRepository.GetAllCompaniesAsync();
                var response = companies.Select(MapToCompanyResponse).ToList();
                return ApiResponse<List<TourismCompanyResponse>>.SuccessResponse(response);
            }
            catch (Exception ex)
            {
                return ApiResponse<List<TourismCompanyResponse>>.ErrorResponse($"Lỗi khi lấy danh sách công ty: {ex.Message}");
            }
        }

        public async Task<ApiResponse<TourismCompanyResponse>> GetCompanyByIdAsync(int id)
        {
            try
            {
                var company = await _companyRepository.GetCompanyByIdAsync(id);
                if (company == null)
                {
                    return ApiResponse<TourismCompanyResponse>.ErrorResponse("Công ty không tồn tại");
                }
                var response = MapToCompanyResponse(company);
                return ApiResponse<TourismCompanyResponse>.SuccessResponse(response);
            }
            catch (Exception ex)
            {
                return ApiResponse<TourismCompanyResponse>.ErrorResponse($"Lỗi khi lấy thông tin công ty: {ex.Message}");
            }
        }

        public async Task<ApiResponse<TourismCompanyResponse>> GetCompanyByUserIdAsync(int userId)
        {
            try
            {
                var company = await _companyRepository.GetCompanyByUserIdAsync(userId);
                if (company == null)
                {
                    return ApiResponse<TourismCompanyResponse>.ErrorResponse("Người dùng chưa có công ty du lịch");
                }
                var response = MapToCompanyResponse(company);
                return ApiResponse<TourismCompanyResponse>.SuccessResponse(response);
            }
            catch (Exception ex)
            {
                return ApiResponse<TourismCompanyResponse>.ErrorResponse($"Lỗi khi lấy công ty theo người dùng: {ex.Message}");
            }
        }

        public async Task<ApiResponse<TourismCompanyResponse>> CreateCompanyAsync(CreateTourismCompanyRequest request)
        {
            try
            {
                // Validate user exists and has Tourism Company role
                var validationResult = await ValidateUserForTourismCompanyAsync(request.UserId);
                if (!validationResult.IsValid)
                {
                    return ApiResponse<TourismCompanyResponse>.ErrorResponse(validationResult.ErrorMessage);
                }

                // Check if user already has a tourism company
                var existingCompany = await _companyRepository.GetCompanyByUserIdAsync(request.UserId);
                if (existingCompany != null)
                {
                    return ApiResponse<TourismCompanyResponse>.ErrorResponse("Người dùng đã có công ty du lịch");
                }

                var company = new TourismCompany
                {
                    // Don't set Id as it's auto-generated by the database
                    CompanyName = request.CompanyName,
                    RepresentativeName = request.RepresentativeName,
                    Email = request.Email,
                    PhoneNumber = request.PhoneNumber,
                    TaxCode = request.TaxCode,
                    UserId = request.UserId // Add UserId
                };
                var createdCompany = await _companyRepository.CreateCompanyAsync(company);
                var response = MapToCompanyResponse(createdCompany);
                return ApiResponse<TourismCompanyResponse>.SuccessResponse(response, "Tạo công ty thành công");
            }
            catch (Exception ex)
            {
                return ApiResponse<TourismCompanyResponse>.ErrorResponse($"Lỗi khi tạo công ty: {ex.Message}");
            }
        }

        public async Task<ApiResponse<TourismCompanyResponse>> UpdateCompanyAsync(UpdateTourismCompanyRequest request)
        {
            try
            {
                var company = await _companyRepository.GetCompanyByIdAsync(request.Id);
                if (company == null)
                {
                    return ApiResponse<TourismCompanyResponse>.ErrorResponse("Công ty không tồn tại");
                }

                // Keep the original company name if not provided
                // Don't update the Id as it's the primary key
                company.RepresentativeName = request.RepresentativeName;
                company.Email = request.Email;
                company.PhoneNumber = request.PhoneNumber;
                company.TaxCode = request.TaxCode;

                await _companyRepository.UpdateCompanyAsync(company);
                var response = MapToCompanyResponse(company);
                return ApiResponse<TourismCompanyResponse>.SuccessResponse(response, "Cập nhật công ty thành công");
            }
            catch (Exception ex)
            {
                return ApiResponse<TourismCompanyResponse>.ErrorResponse($"Lỗi khi cập nhật công ty: {ex.Message}");
            }
        }

        public async Task<ApiResponse<bool>> DeleteCompanyAsync(int id)
        {
            try
            {
                var result = await _companyRepository.DeleteCompanyAsync(id);
                if (!result)
                {
                    return ApiResponse<bool>.ErrorResponse("Công ty không tồn tại");
                }
                return ApiResponse<bool>.SuccessResponse(true, "Xóa công ty thành công");
            }
            catch (Exception ex)
            {
                return ApiResponse<bool>.ErrorResponse($"Lỗi khi xóa công ty: {ex.Message}");
            }
        }

        public async Task<ApiResponse<bool>> UpdateCompanyStatusAsync(int id, bool isActive)
        {
            try
            {
                var company = await _companyRepository.GetCompanyByIdAsync(id);
                if (company == null)
                {
                    return ApiResponse<bool>.ErrorResponse("Công ty không tồn tại");
                }

                await _companyRepository.UpdateCompanyAsync(company);
                return ApiResponse<bool>.SuccessResponse(true, "Cập nhật trạng thái công ty thành công");
            }
            catch (Exception ex)
            {
                return ApiResponse<bool>.ErrorResponse($"Lỗi khi cập nhật trạng thái công ty: {ex.Message}");
            }
        }

        private async Task<ValidationResult> ValidateUserForTourismCompanyAsync(int userId)
        {
            // Check if user exists
            var user = await _context.Users
                .Include(u => u.UserRoles)
                .ThenInclude(ur => ur.Role)
                .FirstOrDefaultAsync(u => u.UserId == userId);

            if (user == null)
            {
                return new ValidationResult { IsValid = false, ErrorMessage = "Người dùng không tồn tại" };
            }

            // Check if user has Tourism Company role
            var hasTourismCompanyRole = user.UserRoles.Any(ur => ur.Role.RoleName == "Tourism Company");
            if (!hasTourismCompanyRole)
            {
                return new ValidationResult { IsValid = false, ErrorMessage = "Người dùng không có quyền tạo công ty du lịch. Cần có role 'Tourism Company'" };
            }

            return new ValidationResult { IsValid = true };
        }

        private TourismCompanyResponse MapToCompanyResponse(TourismCompany company)
        {
            return new TourismCompanyResponse
            {
                Id = company.Id,
                CompanyId = company.Id,
                CompanyName = company.CompanyName,
                RepresentativeName = company.RepresentativeName,
                Email = company.Email,
                PhoneNumber = company.PhoneNumber,
                TaxCode = company.TaxCode
            };
        }
    }
    public class ValidationResult
    {
        public bool IsValid { get; set; }
        public string ErrorMessage { get; set; }
    }
}